$(function(){
	//添加窗口Resize
	LxExt.Dialog.setBorderDrag(true);
	LxExt.Dialog.borderDrag($("#MyBody"),$("#MyWindow"),5);
	//设置最小大小
	LxExt.Dialog.setMinimumSize(200,200);
	//窗口居中
	LxExt.Dialog.centerWnd();
	//设置窗口的大小
	LxExt.Dialog.initWndWH(200,200);
	LxExt.Dialog.updateClientSize($("#MyBody"),30);
	//设置窗口标题栏目可移动
	LxExt.Dialog.dragRegion($(".DragTitileBar"));
	//添加 最小化，关闭事件
	$("#BtnMin").click(function(){
		LxExt.Dialog.showFullScreen();
	});
	$("#BtnExit").click(function(){
		LxExt.Dialog.closeWnd();
	});
});