# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./resource.h
SOURCES += ./main.cpp
FORMS += ./lomoxtest.ui
RESOURCES += ./lomoxtest.qrc
